// ═════════════════════════════════════════════════════════════
// ■ 大会データ（ここだけ編集すればOK）
//
// この FESTIVALS 配列に1ブロックをコピペして書き換え、main に push すると
// 公開サイトに自動で反映されます（GitHub に push できるのはオーナーだけ）。
// GitHub の Web 画面からこのファイルを直接編集してもOK—PCなしで更新できます。
//
// ── コピペ用テンプレート ──────────────────
// { id:"unique-id",                  // 半角英数のユニークな名前
//   name:"◯◯花火大会", pref:"愛知",  // 愛知/岐阜/三重/静岡/番外
//   date:"2026-08-01",               // 開催日 (YYYY-MM-DD)
//   dateLabel:"8/1(土) 19:00〜",     // 画面に出す日付の文字
//   verified:true,                   // 日程を公式で確認済なら true
//   shells:10000,                    // 打ち上げ数
//   shellsLabel:"約10,000発",
//   durationMin:90,                  // 打ち上げ時間(分)
//   lat:35.0, lon:137.0,             // 緯度・経度（Googleマップで右クリック→コピー）
//   place:"◯◯市 ◯◯河畔",
//   venue:"river",                   // river / sea / lake / park
//   venueLabel:"◯◯川の河畔",
//   maxLabel:"尺玉", maxDiaM:320,    // 名物の玉と開花直径(m)
//   access:"名古屋から:◯◯で約◯分",
//   tickets:[                        // チケット受付期間（自動でステータス判定）
//     { label:"有料席（先着）", type:"sale",    start:"2026-06-13", end:null },
//     { label:"カメラ席（抽選）", type:"lottery", start:"2026-07-07", end:"2026-07-17" },
//   ],                               // start/end 不明なら null（開催日まで受付扱い）
//   ticketNote:"補足メモ",
//   url:"https://...",               // 公式サイト
//   note:"見どころの説明" },
//
// ※ 完売など日付で判定できない状態は statusOverride で上書きできます:
//   statusOverride:{ kind:"soldout", label:"完売" }   // kind: sale/soldout/lottery/upcoming/closed/none/check
// ───────────────────────────────────────────
// ═════════════════════════════════════════════════════════════
export const FESTIVALS = [
  { id:"toyohashi", name:"豊橋祇園祭 打上花火", pref:"愛知",
    date:"2026-07-18", dateLabel:"7/17(金)手筒・7/18(土)打上", verified:true,
    shells:12000, shellsLabel:"約12,000発（例年）", durationMin:110,
    lat:34.78, lon:137.39, place:"豊橋市 豊川河畔・吉田神社",
    venue:"river", venueLabel:"豊川の河畔", maxLabel:"手筒花火＋尺玉", maxDiaM:300,
    access:"名古屋から:名鉄特急で約50分",
    tickets:[], statusOverride:{kind:"soldout", label:"完売"},
    ticketNote:"桟敷席（6,000円）は完売（公式発表）。入手はチケット流通センター等の二次流通のみ",
    url:"https://www.toyohashigion.org/",
    note:"手筒花火発祥の地。初日は境内で手筒、2日目に河畔で打上。" },
  { id:"minato", name:"海の日名古屋みなと祭花火大会", pref:"愛知",
    date:"2026-07-20", dateLabel:"7/20(月・祝 海の日)", verified:true,
    shells:3000, shellsLabel:"約3,000発（例年）", durationMin:35,
    lat:35.09, lon:136.88, place:"名古屋市 名古屋港ガーデンふ頭",
    venue:"sea", venueLabel:"名古屋港の海上台船", maxLabel:"海上打上の尺玉", maxDiaM:320,
    access:"名古屋から:地下鉄名古屋港駅すぐ（市内で最も気軽）",
    tickets:[{label:"有料協賛席", type:"sale", start:null, end:null}],
    ticketNote:"販売状況は公式発表を確認",
    url:"https://hanabi-navi.info/tokai-region/pref-aichi/",
    note:"発数は少なめでも、海上台船からの尺玉とメロディー花火の質が高い都市型花火。" },
  { id:"kuwana", name:"桑名水郷花火大会", pref:"三重",
    date:"2026-07-25", dateLabel:"7/25(土) 19:30〜21:00", verified:true,
    shells:10000, shellsLabel:"約10,000発", durationMin:90,
    lat:35.07, lon:136.69, place:"桑名市 揖斐川河畔(鍋屋堤)",
    venue:"river", venueLabel:"揖斐川の川面", maxLabel:"東海最大級の二尺玉", maxDiaM:600,
    access:"名古屋から:近鉄特急で約20分（桑名駅から徒歩20分）",
    tickets:[], statusOverride:{kind:"soldout", label:"公式販売終了（完売）"},
    ticketNote:"楽天チケットの公式販売は終了（完売とみられる）。例年は当日券エリアの設定例あり。2026年は三重初のドローンショーも",
    url:"https://kuwana-hanabi.com/",
    note:"1934年から続く水郷の花火。直径約600mの二尺玉が名物。" },
  { id:"fukuroi", name:"ふくろい遠州の花火", pref:"静岡",
    date:"2026-07-25", dateLabel:"7/25(土) 19:20〜21:00", verified:true,
    shells:25000, shellsLabel:"約25,000発（例年）", durationMin:100,
    lat:34.75, lon:137.92, place:"袋井市 原野谷川親水公園",
    venue:"river", venueLabel:"原野谷川の河畔", maxLabel:"尺玉・空中ナイアガラ", maxDiaM:320,
    access:"名古屋から:新幹線+JRで約80分（愛野駅・袋井駅から徒歩20分）",
    tickets:[{label:"有料席 約3.1万席（ブロック席5,500円〜）", type:"sale", start:"2026-06-13", end:null}],
    statusOverride:{kind:"sale", label:"販売中（一部完売）"},
    ticketNote:"イス席A〜D(7,500円)・ブロック席(5,500円)は販売中。ペアイス席・カメラ席は完売、ファミリー席は残少（6/29時点）",
    url:"https://www.fukuroi-hanabi.jp/",
    note:"全国の花火名人による選抜競技大会。日本十大花火のひとつ。" },
  { id:"ise", name:"伊勢神宮奉納全国花火大会", pref:"三重",
    date:"2026-07-18", dateLabel:"7/18(土) 19:20〜21:00", verified:true,
    shells:8400, shellsLabel:"約8,400発", durationMin:100,
    lat:34.49, lon:136.7, place:"伊勢市 宮川河畔(度会橋上流)",
    venue:"river", venueLabel:"宮川の河畔", maxLabel:"全国競技会の芸術玉", maxDiaM:280,
    access:"名古屋から:近鉄特急で約85分",
    tickets:[
      {label:"有料観覧席 市民先行（先着）", type:"sale", start:"2026-05-08", end:"2026-05-08"},
      {label:"有料観覧席 一般販売（先着・売切次第終了）", type:"sale", start:"2026-05-09", end:null}],
    ticketNote:"先着順（抽選なし）。個人自由席3,000円〜、指定席(6人)18,000〜21,000円。チケットぴあ・コンビニで販売",
    url:"https://www.city.ise.mie.jp/hanabi/osirase/index.html",
    note:"第74回。日本三大競技花火のひとつ。全国の花火師が神宮に奉納する芸術花火。荒天時は9/5(土)に延期。" },
  { id:"oiden", name:"豊田おいでんまつり花火大会", pref:"愛知",
    date:"2026-07-26", dateLabel:"7/26(日) 19:00〜20:40", verified:true,
    shells:13000, shellsLabel:"約13,000発（例年）", durationMin:100,
    lat:35.08, lon:137.16, place:"豊田市 白浜公園一帯(矢作川)",
    venue:"river", venueLabel:"矢作川の河川敷", maxLabel:"メロディ花火・大ナイアガラ", maxDiaM:300,
    access:"名古屋から:名鉄で約60分（豊田市駅から徒歩10分）",
    tickets:[{label:"個人協賛席 先着受付", type:"sale", start:"2026-07-04", end:null}],
    ticketNote:"抽選受付は終了。残席分の先着受付が7/4開始・販売中（チケットぴあ）。※夏開催は2026年が最後、2027年から秋開催へ変更",
    url:"https://www.oidenmaturi.com/",
    note:"メロディ花火・大手筒・ナイアガラ。中部有数の規模で約35万人が来場。" },
  { id:"gamagori", name:"蒲郡まつり納涼花火大会", pref:"愛知",
    date:"2026-07-26", dateLabel:"7/26(日) 19:30〜21:00（祭は25・26日）", verified:true,
    shells:5000, shellsLabel:"約5,000発（例年）", durationMin:90,
    lat:34.82, lon:137.22, place:"蒲郡市 竹島ふ頭周辺(三河湾)",
    venue:"sea", venueLabel:"三河湾の海上", maxLabel:"正三尺玉×3発（太平洋岸最大級）", maxDiaM:650,
    access:"名古屋から:JR・名鉄で約50分（蒲郡駅から徒歩3分）",
    tickets:[{label:"特別観覧エリア（シングル6,000円〜）", type:"sale", start:"2026-05-27", end:null}],
    ticketNote:"5/27から先着募集中（今年は販売数増）。完売告知なし",
    url:"https://hanabi.walkerplus.com/detail/ar0623e00800/",
    note:"直径約650mに開く正三尺玉が3発。全国でも数えるほどの大玉が海上に咲く。" },
  { id:"okazaki", name:"岡崎城下家康公夏まつり 第78回花火大会", pref:"愛知",
    date:"2026-08-01", dateLabel:"8/1(土) 19:00〜20:30 ※順延なし", verified:true,
    shells:20000, shellsLabel:"約20,000発（例年）", durationMin:90,
    lat:34.95, lon:137.17, place:"岡崎市 乙川・矢作川河畔",
    venue:"river", venueLabel:"乙川河畔・岡崎城を背景に", maxLabel:"三河花火・金魚花火・仕掛花火", maxDiaM:320,
    access:"名古屋から:名鉄で約30分（東岡崎駅・岡崎公園前駅から徒歩10分）",
    tickets:[
      {label:"市民先行販売（抽選）", type:"lottery", start:"2026-06-12", end:"2026-06-29"},
      {label:"一般販売（先着）", type:"sale", start:"2026-07-11", end:null}],
    ticketNote:"市民先行・ふるさと納税枠は受付終了。一般販売は7/11(土)10:00開始（先着・売切次第終了）。打上会場近くに無料観覧エリアなし（チケット必須）",
    url:"https://okazaki-kanko.jp/feature/hanabitaikai/hanabitokusyu",
    note:"三河花火発祥の地・家康公生誕の地の伝統花火。お城×花火の構図は全国的にも希少。" },
  { id:"nagaragawa", name:"ぎふ長良川花火大会", pref:"岐阜",
    date:"2026-08-08", dateLabel:"8/8(土) 19:30〜20:40頃（荒天時8/22延期）", verified:true,
    shells:10000, shellsLabel:"非公表（1万発規模と推定）", durationMin:70,
    lat:35.44, lon:136.77, place:"岐阜市 長良川河畔(長良橋〜金華橋)",
    venue:"river", venueLabel:"長良川・金華山を背景に", maxLabel:"尺玉・ワイドスターマイン", maxDiaM:320,
    access:"名古屋から:JRで約20分+バス（岐阜駅からバス15分）",
    tickets:[{label:"有料観覧席 一般販売（先着）", type:"sale", start:"2026-07-08", end:"2026-08-08"}],
    ticketNote:"市民先行・EX会員先行は終了。一般販売は7/8(水)10:00開始（ネット・セブンイレブン、予定席数に達し次第終了）",
    url:"https://nagara-hanabi.jp/",
    note:"旧「全国選抜長良川中日花火大会」と「全国花火大会」が2023年に統合して誕生した大会。" },
  { id:"tokai", name:"東海まつり花火大会", pref:"愛知",
    date:"2026-08-08", dateLabel:"8/8(土) 19:20〜20:30", verified:true,
    shells:4000, shellsLabel:"約4,000発", durationMin:70,
    lat:35.02, lon:136.9, place:"東海市 大池公園",
    venue:"park", venueLabel:"大池公園の池畔", maxLabel:"大スターマイン", maxDiaM:200,
    access:"名古屋から:名鉄で約25分（太田川駅から徒歩15分）",
    tickets:[{label:"有料観覧席", type:"sale", start:null, end:null}],
    ticketNote:"東海市観光協会サイト参照",
    url:"https://hanabi.walkerplus.com/detail/ar0623e00812/",
    note:"観覧席と打上場所が近く迫力大。大池に映る花火も見どころ。" },
  { id:"nagashima", name:"ナガシマスパーランド 花火大競演", pref:"三重",
    date:"2026-08-09", dateLabel:"8/9〜8/29の間の10日間開催", verified:true,
    shells:3000, shellsLabel:"1夜あたり数千発規模（推定）", durationMin:30,
    lat:35.03, lon:136.73, place:"桑名市 ナガシマスパーランド",
    venue:"park", venueLabel:"遊園地の敷地内", maxLabel:"至近距離のワイド演出", maxDiaM:250,
    access:"名古屋から:名鉄バスセンターから直通バス約50分",
    tickets:[{label:"遊園地入場券で観覧可", type:"sale", start:null, end:"2026-08-29"}],
    ticketNote:"開催日: 8/9,10,11,12,13,14,15,22,23,29",
    url:"https://www.enjoytokyo.jp/event/list/regn08/cat0906/",
    note:"日程の自由度が最大の選択肢。プールや乗り物とセットで楽しめる。" },
  { id:"anjin", name:"按針祭 海の花火大会（伊東）", pref:"静岡",
    date:"2026-08-10", dateLabel:"8/10(月)", verified:true,
    shells:20000, shellsLabel:"約20,000発", durationMin:60,
    lat:34.97, lon:139.09, place:"伊東市 伊東海岸一帯",
    venue:"sea", venueLabel:"伊東の海上ワイド", maxLabel:"海上ワイドスターマイン", maxDiaM:320,
    access:"名古屋から:新幹線+伊東線で約3時間（遠征向き・宿泊推奨）",
    tickets:[{label:"有料席", type:"sale", start:null, end:null}],
    ticketNote:"例年の人出約18万人。宿は早めに",
    url:"https://hanabi.walkerplus.com/launch/ar0600/",
    note:"海上ワイドスターマイン。東海エリア打上数トップクラス。" },
  { id:"bisai", name:"びさい夏まつり 花火大会", pref:"愛知",
    date:"2026-08-08", dateLabel:"8/8(土)", verified:true,
    shells:3000, shellsLabel:"数千発規模（推定）", durationMin:60,
    lat:35.31, lon:136.76, place:"一宮市 木曽川・尾西河川敷グラウンド",
    venue:"river", venueLabel:"木曽川の川面", maxLabel:"川面に上がる大玉", maxDiaM:280,
    access:"名古屋から:JR尾張一宮駅からバス（起方面）",
    tickets:[],
    ticketNote:"有料席情報は公式発表を確認",
    url:"https://www.138ss.com/event/detail/8/",
    note:"旧・濃尾大花火（2022年に廃止）の流れを汲む一宮市側の花火大会。木曽川の川面に大玉が上がる。" },
  { id:"kariya", name:"刈谷わんさか祭り 花火大会", pref:"愛知",
    date:"2026-08-15", dateLabel:"8/15(土) 19:30〜20:15（前夜祭8/14）", verified:true,
    shells:7000, shellsLabel:"約7,000発", durationMin:45,
    lat:35.02, lon:137.0, place:"刈谷市 総合運動公園",
    venue:"park", venueLabel:"総合運動公園の芝生広場", maxLabel:"スターライトシンフォニー＋ドローンショー", maxDiaM:220,
    access:"名古屋から:名鉄で約30分（富士松駅から徒歩圏）",
    tickets:[], statusOverride:{kind:"none", label:"一般有料席なし"},
    ticketNote:"協賛席のみ・一般販売なし。場所取りは前日朝から受付。市制75周年ドローンショーあり",
    url:"https://www.kariya-wansaka.jp/",
    note:"音楽シンクロの「スターライトシンフォニー」が名物。45分に7,000発の高密度打上。" },
  { id:"kumano", name:"熊野大花火大会", pref:"三重",
    date:"2026-08-17", dateLabel:"8/17(月) ※毎年17日固定", verified:true,
    shells:10000, shellsLabel:"約10,000発", durationMin:105,
    lat:33.9, lon:136.12, place:"熊野市 七里御浜海岸・鬼ヶ城",
    venue:"sea", venueLabel:"七里御浜の海上・鬼ヶ城", maxLabel:"三尺玉海上自爆・鬼ヶ城大仕掛け", maxDiaM:600,
    access:"名古屋から:特急南紀で約3時間／車で約2時間半（宿泊推奨）",
    tickets:[
      {label:"浜席 一般発売（先着）", type:"sale", start:"2026-07-01", end:"2026-08-16"},
      {label:"協賛観覧席・カメラ席（抽選）", type:"lottery", start:"2026-07-07", end:"2026-07-17"}],
    ticketNote:"浜席はチケットぴあで販売中（〜8/16 17:00）。堤防席限定抽選は受付終了。ふるさと納税枠もあり",
    url:"https://www.kumano-kankou.info/kumano-fireworks/",
    note:"世界遺産・鬼ヶ城の岩場で炸裂する大仕掛けは全身に響く迫力。" },
  { id:"kihoku", name:"きほく燈籠祭", pref:"三重",
    date:"2026-07-25", dateLabel:"7/25(土) 19:30〜20:30", verified:true,
    shells:3000, shellsLabel:"約3,000発", durationMin:60,
    lat:34.21, lon:136.34, place:"紀北町 長島港",
    venue:"sea", venueLabel:"長島港の海上", maxLabel:"彩雲孔雀（幅約450mの水中花火）", maxDiaM:450,
    access:"名古屋から:車で約2時間",
    tickets:[], statusOverride:{kind:"none", label:"有料席なし・無料観覧"},
    ticketNote:"有料観覧席なし。車いす専用観覧席の事前予約は受付終了",
    url:"https://touroumaturi.com/",
    note:"巨大燈籠と海上花火「彩雲孔雀」が名物。荒天時は翌7/26(日)に順延。" },
  { id:"abekawa", name:"安倍川花火大会", pref:"静岡",
    date:"2026-07-18", dateLabel:"7/18(土) 19:30〜21:00", verified:true,
    shells:15000, shellsLabel:"約10,000〜15,000発", durationMin:90,
    lat:34.96, lon:138.37, place:"静岡市 安倍川河畔",
    venue:"river", venueLabel:"安倍川の河川敷", maxLabel:"大スターマイン連発", maxDiaM:300,
    access:"名古屋から:新幹線で静岡駅約60分+バス",
    tickets:[], statusOverride:{kind:"none", label:"有料席なし・無料観覧"},
    ticketNote:"有料観覧席なし（全席無料で観覧可能）",
    url:"https://www.city.shizuoka.lg.jp/s9635/s006369.html",
    note:"第73回。静岡市最大の花火大会。広い河川敷でゆったり観覧しやすい。荒天中止（延期なし）。" },
  { id:"numazu", name:"沼津夏まつり・狩野川花火大会", pref:"静岡",
    date:"2026-07-25", dateLabel:"7/25(土)・26(日) 19:10〜20:10", verified:true,
    shells:12000, shellsLabel:"約12,000発（2日間計）", durationMin:60,
    lat:35.09, lon:138.86, place:"沼津市 狩野川河川敷",
    venue:"river", venueLabel:"市街地ど真ん中の狩野川", maxLabel:"市街地至近の大スターマイン", maxDiaM:250,
    access:"名古屋から:新幹線+東海道線で約100分",
    tickets:[
      {label:"マス席・プレミアム席（抽選先行）", type:"lottery", start:"2026-06-19", end:"2026-06-26"}],
    ticketNote:"抽選先行（楽天チケット）は受付終了。追加販売の有無は公式で要確認",
    url:"https://hanabi.walkerplus.com/detail/ar0622e00888/",
    note:"第79回。市街地の橋の間で上がるため、街と花火の距離が近い。会場はJR沼津駅南口から徒歩10分。" },
  { id:"atami", name:"熱海海上花火大会", pref:"静岡",
    date:"2026-07-20", dateLabel:"夏季は7/20・7/26・8/5・8/9・8/18・8/24開催 20:15〜20:40", verified:true,
    shells:5000, shellsLabel:"約5,000発／回（例年）", durationMin:25,
    lat:35.1, lon:139.07, place:"熱海市 熱海湾(サンビーチ〜熱海港)",
    venue:"sea", venueLabel:"三方を山に囲まれた熱海湾", maxLabel:"大空中ナイアガラ（フィナーレ）", maxDiaM:300,
    access:"名古屋から:新幹線ひかりで約80分",
    tickets:[], statusOverride:{kind:"none", label:"一般有料席なし"},
    ticketNote:"2026年は一般向け有料観覧席なし。参加宿泊施設の宿泊者専用観覧席あり（施設でレジャーシート配布）",
    url:"https://www.ataminews.gr.jp/event/8/",
    note:"すり鉢状の地形に音が反響する「花火のスタジアム」。夏季6日程で予定を合わせやすい。温泉宿泊とセットが定番。雨天決行。" },
  { id:"biwako", name:"びわ湖大花火大会（番外・滋賀）", pref:"番外",
    date:"2026-08-06", dateLabel:"8/6(木) 19:30〜20:30", verified:true,
    shells:12000, shellsLabel:"約12,000発（予定）", durationMin:60,
    lat:35.0, lon:135.87, place:"大津市 びわ湖畔(大津港沖)",
    venue:"lake", venueLabel:"びわ湖の湖上", maxLabel:"湖面を使った水中スターマイン", maxDiaM:300,
    access:"名古屋から:新幹線+在来線で約70分（京都経由・大津駅）",
    tickets:[
      {label:"有料観覧席 一般発売（先着）", type:"sale", start:"2026-05-23", end:null}],
    ticketNote:"第40回記念大会。イス席7,500円〜、台船正面席13,000円など。高額席を中心に完売進行中。抽選先行（4月）は終了",
    url:"https://www.biwako-visitors.jp/hanabi/outline/",
    note:"第40回記念大会。東海4県外だが名古屋から約70分。湖面反射の水中花火が名物。" },
];
